rules = [
  (r'\"\"\"', 'TRIPLEQUOTE'),
  (r'\'\'\'', 'TRIPLEQUOTE'),
  (r'return\s', 'RETURN'),
  (r'continue\n', 'CONTINUE'),
  (r'break\w', 'BREAK ERR'),
  (r'break\n', 'BREAK NEWLINE'),
  (r'if\s', 'IF'),
  (r'if\(', 'IF LPAREN'),
  (r'else if', 'ELSE IF'),
  (r'else if\(', 'ELSE IF LPAREN'),
  (r'else', 'ELSE'),
  (r'for\s', 'FOR'),
  (r'while', 'WHILE'),
  (r'null', 'NULL'),
  (r'true', 'TRUE'),
  (r'false', 'FALSE'),
  (r'not', 'NOT'),
  (r'and', 'AND'),
  (r'\sor\s', 'OR'),
  (r'\".*\"', 'STRING'),
  (r'\'.*\'', 'STRING'),
  (r':', 'COLON'),
  (r';', 'SEMICOLON'),
  (r'\n', 'NEWLINE'),
  (r'\s', 'WHITESPACE'),
  (r'\d+', 'NUMBER'),
  (r'\d+.+\d', 'FLOAT'),
  (r'[a-zA-Z_]+[\da-zA-Z_0-9]*', 'IDENTIFIER'),
  (r'\+', 'PLUS'),
  (r'\-', 'MINUS'),
  (r'\*', 'MUL'),
  (r'\/', 'DIV'),
  (r'\%', 'MOD'),
  (r'\(', 'LPAREN'),
  (r'\)', 'RPAREN'),
  (r'\[', 'LBRACKET'),
  (r'\]', 'RBRACKET'),
  (r'==', 'DOUBLE_EQUAL'),
  (r'=', 'EQUAL'),
  (r'!=', 'NOT_EQUAL'),
  (r'>=', 'GREATER_OR_EQUAL_THAN'),
  (r'>', 'GREATER_THAN'),
  (r'<=', 'LESS_OR_EQUAL_THAN'),
  (r'<', 'LESS_THAN'),
  (r'\w', 'NULL'),
]